src/WebApp/ViewModels/InventoryManagementViewModel.cs
using System.Collections.Generic;
using WebApp.Models;

namespace WebApp.ViewModels
{
    public class InventoryManagementViewModel
    {
        public IEnumerable<Product> Products { get; set; }
    }
}

src/WebApp/Controllers/InventoryManagementController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using WebApp.Commands;
using WebApp.Mappers;
using WebApp.Models;
using WebApp.RESTClients;
using WebApp.ViewModels;

namespace WebApp.Controllers
{
    public class InventoryManagementController : Controller
    {
        private readonly IInventoryManagementAPI _inventoryManagementAPI;
        private readonly ILogger _logger;
        private ResiliencyHelper _resiliencyHelper;

        public InventoryManagementController(IInventoryManagementAPI inventoryManagementAPI, ILogger<CustomerManagementController> logger)
        {
	        _inventoryManagementAPI = inventoryManagementAPI;
            _logger = logger;
            _resiliencyHelper = new ResiliencyHelper(_logger);
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            return await _resiliencyHelper.ExecuteResilient(async () =>
            {
                var model = new InventoryManagementViewModel
                {
                    Products = await _inventoryManagementAPI.GetProducts()
                };
                return View(model);
            }, View("Offline", new InventoryManagementOfflineViewModel()));
        }

        [HttpGet]
        public async Task<IActionResult> Details(string id)
        {
            return await _resiliencyHelper.ExecuteResilient(async () =>
            {
                var model = new InventoryManagementDetailsViewModel
                {
                    Product = await _inventoryManagementAPI.GetProductById(id)
                };
                return View(model);
            }, View("Offline", new InventoryManagementOfflineViewModel()));
        }

        [HttpGet]
        public IActionResult New()
        {
            var model = new InventoryManagementNewViewModel
            {
                Product = new Product()
            };
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Register([FromForm] InventoryManagementNewViewModel inputModel)
        {
            if (ModelState.IsValid)
            {
                return await _resiliencyHelper.ExecuteResilient(async () =>
                {
                    RegisterProduct cmd = inputModel.MapToRegisterProduct();
                    await _inventoryManagementAPI.RegisterProduct(cmd);
                    return RedirectToAction("Index");
                }, View("Offline", new InventoryManagementOfflineViewModel()));
            }
            else
            {
                return View("New", inputModel);
            }
        }
    }
}

src/WebApp/Views/InventoryManagement/Details.cshtml
@model WebApp.ViewModels.InventoryManagementDetailsViewModel
@{
    ViewData["Title"] = "Inventory Details";
}
<h3 id="PageTitle">Inventory Management - details</h3>

<table class="table">
    <tbody>
        <tr>
            <td width="150">Name :</td>
            <td><b>@Model.Product.Name</b></td>
        </tr>
        <tr>
            <td width="150">Address :</td>
            <td><b>@Model.Product.Price</b></td>
        </tr>
    </tbody>
</table>
<span><a id="BackButton" asp-action="Index" asp-controller="InventoryManagement" class="btn btn-default">Back</a></span>

src/WebApp/Views/InventoryManagement/Index.cshtml
@model WebApp.ViewModels.InventoryManagementViewModel
@{
    ViewData["Title"] = "Inventory Overview";
}
<h3 id="PageTitle">Inventory Management - overview</h3>

<table class="table">
    <thead>
        <tr>
            <th>Name</th>
            <th>Price</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var product in Model.Products)
        {
            <tr class="clickable" onclick="location.href = '@Url.Action("Details", "InventoryManagement", new { id = product.ProductId })'">
                <td>@product.Name</td>
                <td>@product.Price</td>
            </tr>
        }
    </tbody>
</table>
<a id="RegisterProductButton" asp-action="New" asp-controller="InventoryManagement" class="btn btn-default">Register product</a>

src/WebApp/Views/InventoryManagement/New.cshtml
@model WebApp.ViewModels.InventoryManagementNewViewModel
@{
    ViewData["Title"] = "Register Product";
}

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
}

<h3 id="PageTitle">Inventory Management - register product</h3>

<form asp-controller="InventoryManagement" asp-action="Register" method="post">
    <div class="form-group">
        <label asp-for="Product.Name"></label>
        <input asp-for="Product.Name" type="text" class="form-control" />
        <span asp-validation-for="Product.Name" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Product.Price"></label>
        <input asp-for="Product.Price" type="text" class="form-control" />
        <span asp-validation-for="Product.Price" class="text-danger"></span>
    </div>
    <span><button id="SubmitButton" type="submit" class="btn btn-default">Register</button></span>
    <span><a id="CancelButton" asp-action="Index" asp-controller="InventoryManagement" class="btn btn-default">Cancel</a></span>
</form>

src/WebApp/Views/InventoryManagement/Offline.cshtml
@model WebApp.ViewModels.InventoryManagementOfflineViewModel
@{
    ViewData["Title"] = "Offline";
}
<h3 id="PageTitle">Inventory Management - offline</h3>
<p>Unfortunately the Inventory management module is offline at the moment. Try again soon.</p>