src/WebApp/ViewModels/WorkshopManagementViewModel.cs
using System;
using System.Collections.Generic;
using WebApp.Models;

namespace WebApp.ViewModels
{
    public class WorkshopManagementViewModel
    {
        public DateTime Date { get; set; }
        public List<MaintenanceJob> MaintenanceJobs { get; set; }
    }
}

src/WebApp/Controllers/CustomerManagementController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using WebApp.Commands;
using WebApp.Mappers;
using WebApp.Models;
using WebApp.RESTClients;
using WebApp.ViewModels;

namespace WebApp.Controllers
{
    public class CustomerManagementController : Controller
    {
        private readonly ICustomerManagementAPI _customerManagementAPI;
        private readonly ILogger _logger;
        private ResiliencyHelper _resiliencyHelper;

        public CustomerManagementController(ICustomerManagementAPI customerManagementAPI, ILogger<CustomerManagementController> logger)
        {
            _customerManagementAPI = customerManagementAPI;
            _logger = logger;
            _resiliencyHelper = new ResiliencyHelper(_logger);
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            return await _resiliencyHelper.ExecuteResilient(async () =>
            {
                var model = new CustomerManagementViewModel()
                {
                    Customers = await _customerManagementAPI.GetCustomers()
                };
                return View(model);
            }, View("Offline", new CustomerManagementOfflineViewModel()));
        }

        [HttpGet]
        public async Task<IActionResult> Details(string id)
        {
            return await _resiliencyHelper.ExecuteResilient(async () =>
            {
                var model = new CustomerManagementDetailsViewModel
                {
                    Customer = await _customerManagementAPI.GetCustomerById(id)
                };
                return View(model);
            }, View("Offline", new CustomerManagementOfflineViewModel()));
        }

        [HttpGet]
        public IActionResult New()
        {
            var model = new CustomerManagementNewViewModel
            {
                Customer = new Customer()
            };
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Register([FromForm] CustomerManagementNewViewModel inputModel)
        {
            if (ModelState.IsValid)
            {
                return await _resiliencyHelper.ExecuteResilient(async () =>
                {
                    RegisterCustomer cmd = inputModel.MapToRegisterCustomer();
                    await _customerManagementAPI.RegisterCustomer(cmd);
                    return RedirectToAction("Index");
                }, View("Offline", new CustomerManagementOfflineViewModel()));
            }
            else
            {
                return View("New", inputModel);
            }
        }
    }
}

src/WebApp/Controllers/VehicleManagementController.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Logging;
using WebApp.Commands;
using WebApp.Mappers;
using WebApp.Models;
using WebApp.RESTClients;
using WebApp.ViewModels;

namespace WebApp.Controllers
{
    public class VehicleManagementController : Controller
    {
        private IVehicleManagementAPI _vehicleManagementAPI;
        private ICustomerManagementAPI _customerManagementAPI;
        private readonly ILogger _logger;
        private ResiliencyHelper _resiliencyHelper;

        public VehicleManagementController(IVehicleManagementAPI vehicleManagementAPI, 
            ICustomerManagementAPI customerManagementAPI, ILogger<VehicleManagementController> logger)
        {
            _vehicleManagementAPI = vehicleManagementAPI;
            _customerManagementAPI = customerManagementAPI;
            _logger = logger;
            _resiliencyHelper = new ResiliencyHelper(_logger);
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            return await _resiliencyHelper.ExecuteResilient(async () =>
            {
                var model = new VehicleManagementViewModel
                {
                    Vehicles = await _vehicleManagementAPI.GetVehicles()
                };
                return View(model);
            }, View("Offline", new VehicleManagementOfflineViewModel()));
        }

        [HttpGet]
        public async Task<IActionResult> Details(string licenseNumber)
        {
            return await _resiliencyHelper.ExecuteResilient(async () =>
            {
                Vehicle vehicle = await _vehicleManagementAPI.GetVehicleByLicenseNumber(licenseNumber);
                Customer customer = await _customerManagementAPI.GetCustomerById(vehicle.OwnerId);

                var model = new VehicleManagementDetailsViewModel
                {
                    Vehicle = vehicle,
                    Owner = customer.Name
                };
                return View(model);
            }, View("Offline", new VehicleManagementOfflineViewModel()));
        }

        [HttpGet]
        public async Task<IActionResult> New()
        {
            return await _resiliencyHelper.ExecuteResilient(async () =>
            {
                // get customerlist
                var customers = await _customerManagementAPI.GetCustomers();

                var model = new VehicleManagementNewViewModel
                {
                    Vehicle = new Vehicle(),
                    Customers = customers.Select(c => new SelectListItem { Value = c.CustomerId, Text = c.Name })
                };
                return View(model);
            }, View("Offline", new VehicleManagementOfflineViewModel()));
        }

        [HttpPost]
        public async Task<IActionResult> Register([FromForm] VehicleManagementNewViewModel inputModel)
        {
            if (ModelState.IsValid)
            {
                return await _resiliencyHelper.ExecuteResilient(async () =>
                {
                    RegisterVehicle cmd = inputModel.MapToRegisterVehicle();
                    await _vehicleManagementAPI.RegisterVehicle(cmd);
                    return RedirectToAction("Index");
                }, View("Offline", new VehicleManagementOfflineViewModel()));
            }
            else
            {
                return View("New", inputModel);
            }
        }

        [HttpGet]
        public IActionResult Error()
        {
            return View();
        }
    }
}

src/WebApp/Controllers/WorkshopManagementController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Logging;
using Refit;
using WebApp.Commands;
using WebApp.Models;
using WebApp.RESTClients;
using WebApp.ViewModels;

namespace WebApp.Controllers
{
    public class WorkshopManagementController : Controller
    {
        private IWorkshopManagementAPI _workshopManagementAPI;
        private readonly ILogger _logger;
        private ResiliencyHelper _resiliencyHelper;

        public WorkshopManagementController(IWorkshopManagementAPI workshopManagamentAPI, ILogger<WorkshopManagementController> logger)
        {
            _workshopManagementAPI = workshopManagamentAPI;
            _logger = logger;
            _resiliencyHelper = new ResiliencyHelper(_logger);
        }

        [HttpGet]
        public async Task<IActionResult> Index(DateTime? planningDate)
        {
            return await _resiliencyHelper.ExecuteResilient(async () =>
            {
                if (planningDate == null)
                {
                    planningDate = DateTime.Now.Date;
                }

                var model = new WorkshopManagementViewModel
                {
                    Date = planningDate.Value,
                    MaintenanceJobs = new List<MaintenanceJob>()
                };

                // get planning
                string dateStr = planningDate.Value.ToString("yyyy-MM-dd");
                WorkshopPlanning planning = await _workshopManagementAPI.GetWorkshopPlanning(dateStr);
                if (planning?.Jobs?.Count > 0)
                {
                    model.MaintenanceJobs.AddRange(planning.Jobs.OrderBy(j => j.StartTime));
                }

                return View(model);
            }, View("Offline", new WorkshopManagementOfflineViewModel()));
        }

        [HttpGet]
        public async Task<IActionResult> Details(DateTime planningDate, string jobId)
        {
            return await _resiliencyHelper.ExecuteResilient(async () =>
            {
                string dateStr = planningDate.ToString("yyyy-MM-dd");
                var model = new WorkshopManagementDetailsViewModel
                {
                    Date = planningDate,
                    MaintenanceJob = await _workshopManagementAPI.GetMaintenanceJob(dateStr, jobId)
                };
                return View(model);
            }, View("Offline", new WorkshopManagementOfflineViewModel()));
        }

        [HttpGet]
        public async Task<IActionResult> New(DateTime planningDate)
        {
            return await _resiliencyHelper.ExecuteResilient(async () =>
            {
                DateTime startTime = planningDate.Date.AddHours(8);

                var model = new WorkshopManagementNewViewModel
                {
                    Id = Guid.NewGuid(),
                    Date = planningDate,
                    StartTime = startTime,
                    EndTime = startTime.AddHours(2),
                    Vehicles = await GetAvailableVehiclesList()
                };
                return View(model);
            }, View("Offline", new WorkshopManagementOfflineViewModel()));
        }

        [HttpGet]
        public async Task<IActionResult> Finish(DateTime planningDate, string jobId)
        {
            return await _resiliencyHelper.ExecuteResilient(async () =>
            {
                string dateStr = planningDate.ToString("yyyy-MM-dd");
                MaintenanceJob job = await _workshopManagementAPI.GetMaintenanceJob(dateStr, jobId);
                var model = new WorkshopManagementFinishViewModel
                {
                    Id = job.Id,
                    Date = planningDate,
                    ActualStartTime = job.StartTime,
                    ActualEndTime = job.EndTime
                };
                return View(model);
            }, View("Offline", new WorkshopManagementOfflineViewModel()));
        }

        [HttpPost]
        public async Task<IActionResult> RegisterMaintenanceJob([FromForm] WorkshopManagementNewViewModel inputModel)
        {
            if (ModelState.IsValid)
            {
                return await _resiliencyHelper.ExecuteResilient(async () =>
                {
                    string dateStr = inputModel.Date.ToString("yyyy-MM-dd");
                    
                    try
                    {
                        // register maintenance job
                        DateTime startTime = inputModel.Date.Add(inputModel.StartTime.TimeOfDay);
                        DateTime endTime = inputModel.Date.Add(inputModel.EndTime.TimeOfDay);
                        Vehicle vehicle = await _workshopManagementAPI.GetVehicleByLicenseNumber(inputModel.SelectedVehicleLicenseNumber);
                        Customer customer = await _workshopManagementAPI.GetCustomerById(vehicle.OwnerId);

                        PlanMaintenanceJob planMaintenanceJobCommand = new PlanMaintenanceJob(Guid.NewGuid(), Guid.NewGuid(), startTime, endTime,
                            (customer.CustomerId, customer.Name, customer.TelephoneNumber),
                            (vehicle.LicenseNumber, vehicle.Brand, vehicle.Type), inputModel.Description);
                        await _workshopManagementAPI.PlanMaintenanceJob(dateStr, planMaintenanceJobCommand);
                    }
                    catch (ApiException ex)
                    {
                        if (ex.StatusCode == HttpStatusCode.Conflict)
                        {
                            // add errormessage from API exception to model
                            var content = await ex.GetContentAsAsync<BusinessRuleViolation>();
                            inputModel.Error = content.ErrorMessage;

                            // repopulate list of available vehicles in the model
                            inputModel.Vehicles = await GetAvailableVehiclesList();

                            // back to New view
                            return View("New", inputModel);
                        }
                    }

                    return RedirectToAction("Index", new { planningDate = dateStr });
                }, View("Offline", new WorkshopManagementOfflineViewModel()));
            }
            else
            {
                inputModel.Vehicles = await GetAvailableVehiclesList();
                return View("New", inputModel);
            }
        }

        [HttpPost]
        public async Task<IActionResult> FinishMaintenanceJob([FromForm] WorkshopManagementFinishViewModel inputModel)
        {
            if (ModelState.IsValid)
            {
                return await _resiliencyHelper.ExecuteResilient(async () =>
                {
                    string dateStr = inputModel.Date.ToString("yyyy-MM-dd");
                    DateTime actualStartTime = inputModel.Date.Add(inputModel.ActualStartTime.Value.TimeOfDay);
                    DateTime actualEndTime = inputModel.Date.Add(inputModel.ActualEndTime.Value.TimeOfDay);

                    FinishMaintenanceJob cmd = new FinishMaintenanceJob(Guid.NewGuid(), inputModel.Id,
                        actualStartTime, actualEndTime, inputModel.Notes);

                    await _workshopManagementAPI.FinishMaintenanceJob(dateStr, inputModel.Id.ToString("D"), cmd);

                    return RedirectToAction("Details", new { planningDate = dateStr, jobId = inputModel.Id });
                }, View("Offline", new WorkshopManagementOfflineViewModel()));
            }
            else
            {
                return View("Finish", inputModel);
            }
        }

        public IActionResult Error()
        {
            return View();
        }

        private async Task<IEnumerable<SelectListItem>> GetAvailableVehiclesList()
        {
            var vehicles = await _workshopManagementAPI.GetVehicles();
            return vehicles.Select(v =>
                new SelectListItem
                {
                    Value = v.LicenseNumber,
                    Text = $"{v.Brand} {v.Type} [{v.LicenseNumber}]"
                });
        }
    }
}

src/WebApp/Views/WorkshopManagement/Details.cshtml
@model WebApp.ViewModels.WorkshopManagementDetailsViewModel
@{
    ViewData["Title"] = "Planning Details";
}

<h3 id="PageTitle">Workshop Management - details</h3>

<table class="table">
    <tbody>
        <tr>
            <td width="150">Date :</td>
            <td><b>@Model.Date.ToString("dd-MM-yyyy")</b></td>
        </tr>
        <tr>
            <td width="150">Status :</td>
            <td id="JobStatus"><b>@Model.MaintenanceJob.Status</b></td>
        </tr>
        <tr>
            <td width="150">Start time :</td>
            <td><b>@Model.MaintenanceJob.StartTime.ToString("HH:mm")</b></td>
        </tr>
        <tr>
            <td width="150">End time :</td>
            <td><b>@Model.MaintenanceJob.EndTime.ToString("HH:mm")</b></td>
        </tr>
        <tr>
            <td width="150">Description :</td>
            <td><b>@Model.MaintenanceJob.Description</b></td>
        </tr>
        <tr>
            <td width="150">Vehicle :</td>
            <td><b><a href='@Url.Action("Details", "VehicleManagement", new { licenseNumber = Model.MaintenanceJob.Vehicle.LicenseNumber })'>@Model.MaintenanceJob.Vehicle.Brand @Model.MaintenanceJob.Vehicle.Type [@Model.MaintenanceJob.Vehicle.LicenseNumber]</a></b></td>
        </tr>
        <tr>
            <td width="150">Owner :</td>
            <td><b><a href='@Url.Action("Details", "CustomerManagement", new { id = Model.MaintenanceJob.Customer.CustomerId })'>@Model.MaintenanceJob.Customer.Name [@Model.MaintenanceJob.Customer.TelephoneNumber]</a></b></td>
        </tr>
        @if (Model.MaintenanceJob.Status != "Planned")
        {
            <tr>
                <td width="150">Actual Start time :</td>
                <td><b>@Model.MaintenanceJob.ActualStartTime</b></td>
            </tr>
            <tr>
                <td width="150">Actual End time :</td>
                <td><b>@Model.MaintenanceJob.ActualEndTime</b></td>
            </tr>
            <tr>
                <td width="150">Mechanic notes :</td>
                <td><b>@Model.MaintenanceJob.Notes</b></td>
            </tr>
        }
    </tbody>
</table>
<span><a id="BackButton" asp-action="Index" asp-controller="WorkshopManagement" asp-route-planningDate="@Model.Date.ToString("yyyy-MM-dd")" class="btn btn-default">Back</a></span>
@if (Model.MaintenanceJob.Status != "Completed" )
{ 
    <span><a id="CompleteButton" asp-action="Finish" asp-controller="WorkshopManagement" asp-route-planningDate="@Model.Date.ToString("yyyy-MM-dd")" asp-route-jobId="@Model.MaintenanceJob.Id" class="btn btn-default">Complete</a></span>
}

src/WebApp/Views/WorkshopManagement/Finish.cshtml
@model WebApp.ViewModels.WorkshopManagementFinishViewModel
@{
    ViewData["Title"] = "Finish Maintenance job";
}

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
}

<h3 id="PageTitle">Workshop Management - finish maintenance job</h3>

<form asp-controller="WorkshopManagement" asp-action="FinishMaintenanceJob" method="post">
    <div class="form-group">
        <label asp-for="ActualStartTime"></label>
        <input asp-for="ActualStartTime" type="text" class="form-control" />
        <span asp-validation-for="ActualStartTime" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="ActualEndTime"></label>
        <input asp-for="ActualEndTime" type="text" class="form-control" />
        <span asp-validation-for="ActualEndTime" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Notes"></label>
        <input asp-for="Notes" type="text" class="form-control" />
        <span asp-validation-for="Notes" class="text-danger"></span>
    </div>
    <input asp-for="Date" type="hidden" />
    <input asp-for="Id" type="hidden" />
    <span><button id="CompleteButton" type="submit" class="btn btn-default">Complete</button></span>
    <span><a id="BackButton" asp-action="Details" asp-controller="WorkshopManagement" asp-route-planningDate="@Model.Date.ToString("yyyy-MM-dd")" asp-route-jobId="@Model.Id" class="btn btn-default">Cancel</a></span>
</form>

src/WebApp/Views/WorkshopManagement/Index.cshtml
@model WebApp.ViewModels.WorkshopManagementViewModel
@{
    ViewData["Title"] = "Workshop Management";
}
<h3 id="PageTitle">Workshop Management - overview</h3>

<div style="margin-top: 10px; margin-bottom: 10px;">
    <a asp-action="Index" asp-controller="WorkshopManagement" asp-route-planningDate="@Model.Date.AddDays(-1).ToString("yyyy-MM-dd")" class="btn btn-default"><</a>
    <span class="text-primary"><b>@Model.Date.ToString("dd-MM-yyyy")</b></span>
    <a asp-action="Index" asp-controller="WorkshopManagement" asp-route-planningDate="@Model.Date.AddDays(1).ToString("yyyy-MM-dd")" class="btn btn-default">></a>
    <a asp-action="Index" asp-controller="WorkshopManagement" asp-route-planningDate="@DateTime.Now.ToString("yyyy-MM-dd")" class="btn btn-default">Today</a>
</div>

<table class="table">
    <thead>
        <tr>
            <th>Status</th>
            <th>Start Time</th>
            <th>End Time</th>
            <th>Vehicle</th>
            <th>Description</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var job in Model.MaintenanceJobs)
        {
            <tr class="clickable @(job.Status == "Completed" ? "completedjob" : "")" onclick="location.href = '@Url.Action("Details", "WorkshopManagement", new { planningDate = Model.Date.ToString("yyyy-MM-dd"), jobId = job.Id })'">
                <td>@job.Status</td>
                <td>@job.StartTime.ToString("HH:mm")</td>
                <td>@job.EndTime.ToString("HH:mm")</td>
                <td>@job.Vehicle.Brand @job.Vehicle.Type [@job.Vehicle.LicenseNumber]</td>
                <td>@job.Description</td>
            </tr>
        }
    </tbody>
</table>
@if(Model.Date.Date >= DateTime.Now.Date)
{
    <a id="RegisterMaintenanceJobButton" asp-action="New" asp-controller="WorkshopManagement" asp-route-planningDate="@Model.Date.ToString("yyyy-MM-dd")" class="btn btn-default">Schedule Maintenance</a>
}

src/WebApp/Views/WorkshopManagement/New.cshtml
@model WebApp.ViewModels.WorkshopManagementNewViewModel
@{
    ViewData["Title"] = "Schedule Maintenance";
}

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
}

<h3 id="PageTitle">Workshop Management - schedule maintenance</h3>

@if (!string.IsNullOrEmpty(Model.Error))
{
    <div class="well-sm alert-danger">
        <label>Unable to register: @Model.Error</label>
    </div>
}


<form asp-controller="WorkshopManagement" asp-action="RegisterMaintenanceJob" method="post">
    <div class="form-group">
        <label asp-for="StartTime"></label>
        <input asp-for="StartTime" type="text" class="form-control" />
        <span asp-validation-for="StartTime" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="EndTime"></label>
        <input asp-for="EndTime" type="text" class="form-control" />
        <span asp-validation-for="EndTime" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Description"></label>
        <input asp-for="Description" type="text" class="form-control" />
        <span asp-validation-for="Description" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="SelectedVehicleLicenseNumber"></label>
        <select asp-for="SelectedVehicleLicenseNumber" asp-items="Model.Vehicles" class="form-control"></select>
        <span asp-validation-for="SelectedVehicleLicenseNumber" class="text-danger"></span>
    </div>
    <input asp-for="Date" type="hidden" />
    <span><button id="SubmitButton" type="submit" class="btn btn-default">Register</button></span>
    <span><a id="CancelButton" asp-action="Index" asp-route-planningDate="@Model.Date.ToString("yyyy-MM-dd")" asp-controller="WorkshopManagement" class="btn btn-default">Cancel</a></span>
</form>

src/WebApp/Views/WorkshopManagement/Offline.cshtml
@model WebApp.ViewModels.WorkshopManagementOfflineViewModel
@{
    ViewData["Title"] = "Offline";
}
<h3 id="PageTitle">Workshop Management - offline</h3>
<p>Unfortunately the workshop management module is offline at the moment. Try again soon.</p>